services:
  - type: web
    name: clubbee-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables in Render dashboard:
    # - MONGODB_URI
    # - FIREBASE_PROJECT_ID  
    # - FIREBASE_CLIENT_EMAIL
    # - FIREBASE_PRIVATE_KEY
    # - FRONTEND_URL